services:
  - docker

script:
  - docker-compose -f docker-compose-dev.yml run api python manage.py test

after_success:
  - docker build -t jiaqiwang118/coursesreviews-frontend ./frontend
  - docker build -t jiaqiwang118/coursesreviews-backend ./coursebackend
  - docker build -t jiaqiwang118/coursesreviews-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jiaqiwang118/coursesreviews-frontend
  - docker push jiaqiwang118/coursesreviews-backend
  - docker push jiaqiwang118/coursesreviews-nginx

deploy:
  provider: elasticbeanstalk
  region: $AWS_REGION
  app: $APP_NAME
  env: $ENV_NAME
  bucket_name: $S3_BUCKET_NAME
  bucket_path: $APP_NAME
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY