version: '3'
services:
  api:
    image: "jiaqiwang118/coursesreviews-backend"
    mem_limit: 1024m
    hostname: api
    entrypoint: /app/entrypoint.sh
    environment:
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
    volumes:
      - static_volume:/app/django_static
  frontend:
    image: "jiaqiwang118/coursesreviews-frontend"
    mem_limit: 1024m
    hostname: frontend
  nginx:
    image: "jiaqiwang118/coursesreviews-nginx"
    mem_limit: 1024m
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/django_static
volumes:
  static_volume:
