version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/entrypoint-dev.sh
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 3000:3000
  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend