version: '2'

services:
    nginx:
        restart: unless-stopped
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - react-build:/usr/share/nginx/html
            - static_volume:/app/backend/coursebackend/django_static
            - ./docker/nginx/production:/etc/nginx/conf.d
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        depends_on:
            - backend
            - frontend
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/entrypoint.sh
        volumes:
            - static_volume:/app/backend/coursebackend/django_static
        expose:
            - 8000
    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile
        volumes:
            - react-build:/app/frontend/build
volumes:
    static_volume: {}
    react-build:
