version: "3"

services:
  backend:
    build:
      context: ./coursebackend
    command: gunicorn coursebackend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - react-build:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.config:/etc/nginx/conf.d/default.conf:ro
      - react-build:/var/www/react
      depends_on:
        - backend
        - frontend
volume:
  react-build
