version: "3"

services:
  db:
    image: postgres:buster
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: ./coursebackend
      dockerfile: Dockerfile.dev
    entrypoint: /app/entrypoint-dev.sh
    volumes:
      - ./coursebackend:/app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - SECRET_KEY=devsecretkey
      - DEBUG=1
    depends_on:
      - db
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./frontend:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "5000:80"
    depends_on:
      - api
      - frontend