version: "3"

services:
  backend:
    restart: unless-stopped
    build:
      context: ./coursebackend
    volumes:
      - django-static:/coursebackend/static_cdn/static_root
    expose:
      - 8000
  frontend:
    build:
      context: ./frontend
    volumes:
      - react-build:/frontend/build
  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - django-static:/django_static
      - react-build:/var/www/react
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  react-build:
  django-static:
