version: "3"

services:
  backend:
    build:
      context: ./coursebackend
    volumes:
      - ./coursebackend/static_cdn/static_root:/coursebackend/static_cdn/static_root
  frontend:
    build:
      context: ./frontend
    volumes:
      - react-build:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./coursebackend/static_cdn/static_root:/django_static
      - react-build:/var/www/react
    depends_on:
      - backend
      - frontend
volumes:
  react-build:
