# Generated by Django 3.2 on 2021-10-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_last_name',
            field=models.CharField(max_length=20),
        ),
    ]
